apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  labels:
     app: $APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
      - name: sample-ctr
        image: devopstrainer/java-mvn-privaterepo:2
        ports:
        - containerPort: 8080
apiVersion: v1
kind: Service
metadata:
  labels: 
      app: $APP_NAME
spec:
  selector:
    app: $APP_NAME
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  type: NodePort
